In [30]:
import numpy as np
import pandas as pd

# Loading the dataset

In [41]:
m_pd = pd.read_csv("../datasets/labelled_training_data.csv")
c_pd = m_pd.copy()
c_pd

,timestamp,processId,threadId,parentProcessId,userId,mountNamespace,processName,hostName,eventId,eventName,stackAddresses,argsNum,returnValue,args,sus,evil
0,1809.495787,381,7337,1,100,4026532231,close,ip-10-100-1-120,157,prctl,"[140662171848350, 11649800180280676]",5,0,"[{'name': 'option', 'type': 'int', 'value': 'P...",1,0
1,1809.495832,381,7337,1,100,4026532231,close,ip-10-100-1-120,3,close,[140662171777451],1,0,"[{'name': 'fd', 'type': 'int', 'value': 19}]",1,0
2,1809.495921,381,7337,1,100,4026532231,close,ip-10-100-1-120,1010,sched_process_exit,[],0,0,[],1,0
3,1894.139651,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,21,access,[],2,-2,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
4,1894.142127,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,1005,security_file_open,"[139778263990104, 139778263906698]",4,0,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763139,324.542553,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1003,cap_capable,[],1,0,"[{'name': 'cap', 'type': 'int', 'value': 'CAP_...",0,0
763140,324.542579,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,62,kill,[],2,0,"[{'name': 'pid', 'type': 'pid_t', 'value': 0},...",0,0
763141,324.543178,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763142,324.543695,7275,7275,1,109,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763143,324.543831,7108,7108,1,0,4026531840,sshd,ip-10-100-1-79,3,close,[140129105123719],1,0,"[{'name': 'fd', 'type': 'int', 'value': 6}]",0,0

In [12]:
c_pd

,timestamp,processId,threadId,parentProcessId,userId,mountNamespace,processName,hostName,eventId,eventName,stackAddresses,argsNum,returnValue,args,sus,evil
0,1809.495787,381,7337,1,100,4026532231,close,ip-10-100-1-120,157,prctl,"[140662171848350, 11649800180280676]",5,0,"[{'name': 'option', 'type': 'int', 'value': 'P...",1,0
1,1809.495832,381,7337,1,100,4026532231,close,ip-10-100-1-120,3,close,[140662171777451],1,0,"[{'name': 'fd', 'type': 'int', 'value': 19}]",1,0
2,1809.495921,381,7337,1,100,4026532231,close,ip-10-100-1-120,1010,sched_process_exit,[],0,0,[],1,0
3,1894.139651,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,21,access,[],2,-2,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
4,1894.142127,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,1005,security_file_open,"[139778263990104, 139778263906698]",4,0,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763139,324.542553,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1003,cap_capable,[],1,0,"[{'name': 'cap', 'type': 'int', 'value': 'CAP_...",0,0
763140,324.542579,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,62,kill,[],2,0,"[{'name': 'pid', 'type': 'pid_t', 'value': 0},...",0,0
763141,324.543178,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763142,324.543695,7275,7275,1,109,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763143,324.543831,7108,7108,1,0,4026531840,sshd,ip-10-100-1-79,3,close,[140129105123719],1,0,"[{'name': 'fd', 'type': 'int', 'value': 6}]",0,0

In [40]:
c_pd

,timestamp,processId,threadId,parentProcessId,userId,mountNamespace,processName,hostName,eventId,eventName,stackAddresses,argsNum,returnValue,args,sus,evil
0,1809.495787,381,7337,1,100,4026532231,close,ip-10-100-1-120,157,prctl,"[140662171848350, 11649800180280676]",5,0,"[{'name': 'option', 'type': 'int', 'value': 'P...",1,0
1,1809.495832,381,7337,1,100,4026532231,close,ip-10-100-1-120,3,close,[140662171777451],1,0,"[{'name': 'fd', 'type': 'int', 'value': 19}]",1,0
2,1809.495921,381,7337,1,100,4026532231,close,ip-10-100-1-120,1010,sched_process_exit,[],0,0,[],1,0
3,1894.139651,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,21,access,[],2,-2,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
4,1894.142127,7347,7347,7341,0,4026531840,sh,ip-10-100-1-120,1005,security_file_open,"[139778263990104, 139778263906698]",4,0,"[{'name': 'pathname', 'type': 'const char*', '...",1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763139,324.542553,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1003,cap_capable,[],1,0,"[{'name': 'cap', 'type': 'int', 'value': 'CAP_...",0,0
763140,324.542579,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,62,kill,[],2,0,"[{'name': 'pid', 'type': 'pid_t', 'value': 0},...",0,0
763141,324.543178,7274,7274,7108,0,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763142,324.543695,7275,7275,1,109,4026531840,sshd,ip-10-100-1-79,1010,sched_process_exit,[],0,0,[],0,0
763143,324.543831,7108,7108,1,0,4026531840,sshd,ip-10-100-1-79,3,close,[140129105123719],1,0,"[{'name': 'fd', 'type': 'int', 'value': 6}]",0,0

# Visualizing groups

In [42]:
namespace_visualization = c_pd.groupby("mountNamespace")["processName"].value_counts()
namespace_visualization

mountNamespace  processName
4026531840      ps                 406313
                sshd                91762
                systemd-journal     20421
                systemd             17310
                systemd-tmpfile     13014
                amazon-ssm-agen      4850
                snapd                4187
                cron                 4080
                systemd-user-ru      1276
                (tmpfiles)           1008
                ssm-agent-worke       822
                poweroff              754
                (time-dir)            702
                (sd-sync)             523
                sh                    119
                run-parts             112
                journal-offline        96
                kworker/dying          76
                packagekitd            14
                dbus-daemon            11
                gdbus                   7
                gmain                   7
                atd                     6
                containerd-shim         5
                docker                  5
                dockerd                 5
                kworker/u30:1           4
                (sd-pam)                4
                kworker/u30:0           2
                kworker/u30:2           1
4026532217      systemd-udevd      189292
4026532229      systemd-timesyn      1208
4026532231      systemd-network      1112
                close                  36
4026532232      systemd-resolve      3398
4026532288      systemd-logind        602
Name: count, dtype: int64

In [48]:
c_pd[c_pd.loc[:, "sus"] == 1].groupby("mountNamespace")["processName"].value_counts()

mountNamespace  processName
4026531840      systemd        992
                sh             119
                run-parts      112
                atd              6
                (sd-pam)         4
4026532231      close           36
Name: count, dtype: int64

In [21]:
namespace_visualization = c_pd.groupby("mountNamespace")[["sus", "evil"]].value_counts()
namespace_visualization

mountNamespace  sus  evil
4026531840      0    0       566263
                1    0         1233
4026532217      0    0       189292
4026532229      0    0         1208
4026532231      0    0         1112
                1    0           36
4026532232      0    0         3398
4026532288      0    0          602
Name: count, dtype: int64

In [29]:
print(f"Process name unique vals: {np.unique(c_pd.loc[:, "processName"], return_counts=True)[0]}")

Process name unique vals: ['(sd-pam)' '(sd-sync)' '(time-dir)' '(tmpfiles)' 'amazon-ssm-agen' 'atd'
 'close' 'containerd-shim' 'cron' 'dbus-daemon' 'docker' 'dockerd' 'gdbus'
 'gmain' 'journal-offline' 'kworker/dying' 'kworker/u30:0' 'kworker/u30:1'
 'kworker/u30:2' 'packagekitd' 'poweroff' 'ps' 'run-parts' 'sh' 'snapd'
 'sshd' 'ssm-agent-worke' 'systemd' 'systemd-journal' 'systemd-logind'
 'systemd-network' 'systemd-resolve' 'systemd-timesyn' 'systemd-tmpfile'
 'systemd-udevd' 'systemd-user-ru']

# Performing small column drops on the copy dataset

In [33]:
c_pd = c_pd.drop(labels=[
    "threadId", 
    "hostName", 
    "eventName", 
    "stackAddresses", 
    "argsNum", 
    "returnValue",
    "processName", 
    "args"
    ], axis=1)